import { Container, Text } from '@mantine/core'
import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <Text>Let&apos;s build this shit</Text>
      </Container>
    </div>
  )
}

export default Home
